# Generated by Django 4.1.3 on 2024-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default=' ', max_length=1000),
        ),
    ]
